name: Docker Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-24.04

        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v4

            - name: Build and push docker image
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Setup buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: kesavamas/woofi-nginx:${{ github.sha }}

            - name: Deploy to EC2 Instance
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_PRIVATE_KEY }}
                  script: |
                      docker stop woofi-nginx || true
                         echo ${{ vars.DOCKERHUB_USERNAME }}/woofi-nginx:${{ github.sha }}
                         docker rm woofi-nginx || true
                         docker pull ${{ vars.DOCKERHUB_USERNAME }}/woofi-nginx:${{ github.sha }}
                         docker run -d --name woofi-nginx  \
                         --network=woofi \
                         -p 80:80 \
                         -v ${HOME}/certs:/etc/nginx/certs \
                         ${{ vars.DOCKERHUB_USERNAME }}/woofi-nginx:${{ github.sha }}
